server:
  port: 9999
spring:
  application:
    name: web
logging:
  level:
    root: info
    com.hnf.honeycomb.mapper: debug
cluster:
  name: my-application
  ip: 192.168.1.229
  port: 9300
maxConnection: 2
## MongoDB
mongo:
  base:
    host: 192.168.1.228
    port: 27017
    username: root
    password: gb.2312
    db: admin
  ftp:
    ip: 192.168.88.224
    port: 21
    user: downloader
    pwd: downloaderfc
  dbs:
    username: root
    password: gb.2312
    db: admin
    hosts:
      - ip: 192.168.99.14
        port: 27017
      - ip: 192.168.99.15
        port: 27017
      - ip: 192.168.99.16
        port: 27017

  user:
    timeLength: 30000
    count: 5
    operationTimeBetween: 60000000000
    ttlMillis: 999999999
    JWT_SECRET: 7786df7fc3a34e26a61c034d5ec8245d
  #远程调用服务器IP
  remote:
    user:
      host: 192.168.99.115
      port: 11111
    virtual:
      host: 192.168.99.115
      port: 8092
  redis:
    host: 192.168.1.229
    port: 6379
    database: 0
    password: gb.2312
    jedis:
      pool:
        max-active: 600
        max-wait: -1ms
        max-idle: 300
        min-idle: 20
    timeout: 6000ms
    saveTime: 1
js:
  locations: classpath:js/countMap.js, classpath:js/countReduce.js