server:
  port: 80

spring:
  application:
    name: spirng-boot-bill
  profiles:
    active: dev

  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true

  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static

  #  data:
  #    mongodb:
  #      uri: mongodb://localhost/bill
  jpa:
    database: MYSQL
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/d_bill?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.xhu.bill.bean
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
